# Generated by Django 5.0.1 on 2024-02-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
